app/accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView, UserRegisterView, MyProfileView, UserUpdateView


app_name='accounts'
urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('update/', UserUpdateView.as_view(), name='update'),
]

app/home/urls.py
from django.urls import path
from .views import IndexView, Category_list, DetailView, Lastest_news, ContactUs, NewCreateView, NewUpdateView, DeleteView, SearchView, DeletePostView

app_name='home'
urlpatterns=[
    path('', IndexView.as_view(), name='home'),
    path('category/<str:slug>/', Category_list.as_view(), name="category" ),
    path('detail/<str:slug>/', DetailView.as_view(), name="detail"),
    path('las_news/<str:slug>/', Lastest_news.as_view(), name="lastnews"),
    path('contact/', ContactUs.as_view(), name="contact"),
    path('newcreate/', NewCreateView.as_view(), name="newcreate"),
    path('newupdate/<str:slug>/', NewUpdateView.as_view(), name="newupdate"),
    path('delete/<str:slug>/', DeleteView.as_view(), name="delete"),
    path('delete-post/<str:slug>/', DeletePostView.as_view(), name="delete-post"),
    path('search/', SearchView.as_view(), name=""),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app.accounts.urls')),
    path('', include('app.home.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator
# Create your models here.


class User(AbstractUser):
    phone=models.CharField(max_length=15, null=True, blank=True)
    avatar=models.ImageField(upload_to='user_avatar', null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'heic'))])


    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def hashing_password(self):
        if not self.password.startswith('pbkdf2_sha256'):
            self.set_password(self.password)

    
    def save(self, *args, **kwargs):
        self.hashing_password()
        return super().save(*args, **kwargs)

app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import TextInput,PasswordInput,EmailInput
from PIL import Image
from .models import User

class CastumAuthForm(AuthenticationForm):
    username=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'email/phone number'}))
    password=forms.CharField(widget=PasswordInput(attrs={'placeholder':'password'}))


class UserRegisterForm(forms.ModelForm):
    username=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'username'}))
    first_name=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'Abdullo'}))
    last_name=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'Istamov'}))
    email=forms.EmailField(widget=EmailInput(attrs={'class':'validate', 'placeholder':'user@user.com'}))
    phone=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'+998937151034'}))
    avatar=forms.ImageField()


    password=forms.CharField(widget=PasswordInput(attrs={'class':'validate', 'placeholder':'password'}))
    confirm_password=forms.CharField(widget=PasswordInput(attrs={'class':'validate', 'placeholder':'confirm password'}))



    class Meta:
        model=User
        fields=('username', 'first_name', 'last_name', 'email', 'phone', 'avatar')



    def clean_username(self):
        username=self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Bu username oldin tizimda ro\'yxatdan o\'tgan')
        return username


    def clean_confirm_password(self):
        password=self.cleaned_data.get('password')
        confirm_password=self.cleaned_data.get('confirm_password')
        if password!=confirm_password:
            raise('Parollar bir biriga mos emas')
        return confirm_password

    
    def save(self, commit=True):
        user=super().save(commit)
        user.set_password(self.cleaned_data['confirm_password'])
        user.save()
        return user


        img=Image.open(user.avatar.path)
        
        if img.height>500 or img.width>500:
            new_img=(350,350)
            img.thumbnail(new_img)
            img.save(user.avatar.path)

            return user



class UserUpdateForm(forms.ModelForm):
    first_name=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'Abdullo'}))
    last_name=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'Istamov'}))
    email=forms.EmailField(widget=EmailInput(attrs={'class':'validate', 'placeholder':'user@user.com'}))
    phone=forms.CharField(widget=TextInput(attrs={'class':'validate', 'placeholder':'+998937151034'}))
    avatar=forms.ImageField()


    class Meta:
        model=User
        fields=('first_name', 'last_name', 'email', 'phone', 'avatar')


     
    def save(self, commit=True):
        user=super().save(commit)
        user.save()


        img=Image.open(user.avatar.path)
        
        if img.height>500 or img.width>500:
            new_img=(350,350)
            img.thumbnail(new_img)
            img.save(user.avatar.path)
        
        return user

app/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import CastumAuthForm, UserRegisterForm, UserUpdateForm
from django.contrib.auth import login, logout
from django.contrib import messages
from .models import User
from PIL import Image

# Create your views here.


class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home:home')
        form=CastumAuthForm
        context={
            'form': form,
        }

        return render(request, 'accounts/login.html', context)

    
    def post(self, request):
        data=request.POST
        form=CastumAuthForm(data=data)
        if form.is_valid():
            user=form.get_user()
            login(request, user)
            messages.success(request, 'Tizimga muvaffaqqiyatli kirdingiz.')
            return redirect('home:home')
        else:
            messages.warning(request, 'Parol yoki login xato.')
            return render(request, 'accounts/login.html', {'form':form})



class LogoutView(View):
    
    def get(self, request):
        logout(request)
        messages.info(request, 'Tizimdan muvaffaqqiyatli chiqtingiz.')
        return redirect('home:home')




class UserRegisterView(View):
    form=UserRegisterForm
    def get(self, request):
        if not request.user.is_authenticated:
                
            context={
                'form':self.form,
            }

            return render(request, 'accounts/register.html', context)
        messages.warning(request, 'Siz avval tizimdan chiqishingiz kerak.')
        return redirect('home:home')

    def post(self, request):
        user_form=self.form(data=request.POST, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Akaunt muvaffaqqiyatli yaratildi.')
            return redirect('home:home')
        messages.warning(request, 'Akaunt yaratilmadi.')
        context={
            'form':user_form,
        }
        return render(request, 'accounts/register.html', context)



class MyProfileView(View):
    def get(self, request):
        if request.user.is_authenticated:
            user=User.objects.get(id=request.user)
            context={
                'user': user,
            }
            return render(request, 'accounts/profile.html', context)
        messages.warning(request, 'Siz oldin Login qilishingiz kerak.')
        return redirect('accounts:login')




class UserUpdateView(View):
    form=UserUpdateForm
    def get(self, request):
        if request.user.is_authenticated:
            user=User.objects.get(id=request.user)
            context={
                'form': self.form(instance=user),
            }
            return render(request, 'accounts/update.html', context)

        messages.warning(request, 'Siz oldin tizimga kirishingiz kerak.')
        return redirect('home:home')

    def post(self, request):
        user_form=self.form(data=request.POST, files=request.FILES, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Akaunt muvaffaqiyatli yangilandi.')
            return redirect('home:home')
        messages.warning(request, 'Akaunt yangilanmadi.')
        context={
            'form': user_form,
        }
        return render(request, 'accounts/update.html', context)

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Sign In
{% endblock title %}

{% block content %}


<h2>Please Sign In</h2>

    <form method="post">
        {% csrf_token %}
        
        <div class="container">
            <h3>username</h3>
            {{ form.username }}
        </div>
        <br>
        <div class="container">
            <h3>password</h3>
            {{ form.password }}
        </div>
        <br>
        <div class="container">
            <input type="submit" value="Log In" class="btn btn-warning"><br>
        </div>
    </form>
    
<div class="container">
    <a href="{% url 'home:home' %}" class="btn btn-info">Back</a>
</div>


{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Profile
{% endblock title %}


{% block content %}

<h2>Your Profile</h2>

    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="Profile picture" style="width: 200px; height: 200px; border-radius: 50%;">
    {% endif %}


    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Phone: {{ user.phone }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Date Joined: {{ user.date_jonied }}</p>
    

<a href="{% url 'accounts:update' %}" class="btn btn-primary">Update</a>
<a href="{% url 'home:home' %}" class="btn btn-info">Back</a>

{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Register
{% endblock title %}

{% block content %}

<h2>Please Register</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Register" class="btn btn-success">
    </form>
    
<a href="{% url 'home:home' %}" class="btn btn-info">Back</a>

{% endblock content %}

templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Update
{% endblock title %}


{% block content %}

<h2>Please Update</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Update" class="btn btn-success">
    </form>
    
<a href="{% url 'home:home' %}" class="btn btn-info">Back</a>

{% endblock content %}