app/accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView, UserRegisterView, MyProfileView, UserUpdateView


app_name='accounts'
urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('update/', UserUpdateView.as_view(), name='update'),
]

app/home/urls.py
from django.urls import path
from .views import IndexView, Category_list, DetailView, Lastest_news, ContactUs, NewCreateView, NewUpdateView, DeleteView, SearchView, DeletePostView

app_name='home'
urlpatterns=[
    path('', IndexView.as_view(), name='home'),
    path('category/<str:slug>/', Category_list.as_view(), name="category" ),
    path('detail/<str:slug>/', DetailView.as_view(), name="detail"),
    path('las_news/<str:slug>/', Lastest_news.as_view(), name="lastnews"),
    path('contact/', ContactUs.as_view(), name="contact"),
    path('newcreate/', NewCreateView.as_view(), name="newcreate"),
    path('newupdate/<str:slug>/', NewUpdateView.as_view(), name="newupdate"),
    path('delete/<str:slug>/', DeleteView.as_view(), name="delete"),
    path('delete-post/<str:slug>/', DeletePostView.as_view(), name="delete-post"),
    path('search/', SearchView.as_view(), name=""),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app.accounts.urls')),
    path('', include('app.home.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap Ecommerce Template" name="keywords">
        <meta content="Bootstrap Ecommerce Template Free Download" name="description">

        <!--  -->
        <link href="{% static 'img/noun.svg' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">
        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top Header Start -->
        <div class="top-header">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-4">
                        <div class="logo">
                            <a href="{% url 'home:home' %}">
                                <img src="{% static 'img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="container">
                            <form method="GET" action="{% url 'home:home' %}">
                                <input type="text" placeholder="Search" name="query">
                                <button type="submit"><i class="btn btn-primary"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4">
                        <div class="social">
                            <a href="{{ about.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a>
                            <a href="{{ about.facebook }}" target="_blank"><i class="fab fa-facebook"></i></a>
                            <a href="{{ about.linkedin }}" target="_blank"><i class="fab fa-linkedin"></i></a>
                            <a href="{{ about.instagram }}" target="_blank"><i class="fab fa-instagram"></i></a>
                            <a href="{{ about.youtube }}" target="_blank"><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Header End -->


        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}



        
        <!-- Header Start -->
        <div class="header">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="{% url 'home:home' %}" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav m-auto">
                          {% block menu %}
                            
                          {% endblock menu %}
                            
                            {% if user.is_authenticated %}
                                <a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Chiqish</a>
                                <a href="{% url 'home:newcreate' %}" class="nav-item nav-link">Qo'shish</a>
                            {% else %}
                                <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Kirish</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Header End -->


        {% block content %}
        {% endblock content %}


        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">

                    <!-- category bar -->
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget" style="padding-left: 30%;">
                            <h3 class="title">Category</h3>
                            <ul>
                                {% for category in kategoriyalar %}
                                    <li>
                                        <li><span class="fa-li"><i class="far fa-arrow-alt-circle-right"></i></span><a href="{% url 'home:category' category.slug %}">{{ category.name }}</a></li>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <!-- Tags bar -->
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget" style="padding-left: 30%;">
                            <h3 class="title">Tags</h3>
                            <ul>
                                {% for tag in tags %}
                                    <li>
                                        <li><span class="fa-li"><i class="far fa-arrow-alt-circle-right"></i></span><a href="//?query={{ tag.name }}">{{ tag.name }}</a></li>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget" style="padding-left: 30%;">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>{{ about.locations }}</p>
                                <p><i class="fa fa-envelope"></i>{{ about.email }}</p>
                                <p><i class="fa fa-phone"></i>{{ about.phone }}</p>
                                <div class="social">
                                    <a href="{{ about.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a>
                                    <a href="{{ about.facebook }}" target="_blank"><i class="fab fa-facebook"></i></a>
                                    <a href="{{ about.linkedin }}" target="_blank"><i class="fab fa-linkedin"></i></a>
                                    <a href="{{ about.instagram }}" target="_blank"><i class="fab fa-instagram"></i></a>
                                    <a href="{{ about.youtube }}" target="_blank"><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget" style="padding-left: 35%;">
                            <h3 class="title" style="padding-left: 50;">Newsletter</h3>
                            <div class="newsletter">
                                <p>Biz bilan bog'lanish uchun manzil qoldiring.</p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
        

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p><a href="#">Abdullo Istamov</a>. All Rights </p>
                    </div>

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    <div class="col-md-6 template-by">
                        <p>By<a href="#"> Abdullo Istamov</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->


        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>


        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>


        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
category page
{% endblock title %}


{% block menu %}
    <a href="{% url 'home:home' %}" class="nav-item nav-link ">Home</a>
    {% for category in kategoriyalar %}
        <a href="{% url 'home:category' category.slug %}" class="nav-item nav-link {% if category.slug == ctg.slug %} active {% endif %}" >{{ category.name }}</a>
    {% endfor %}

    <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
{% endblock menu %}


{% block content %}

 <h1><b>{{ ctg.name }} - Categoriyasi</b></h1>

 <br>
 <hr>
 <br>
 <br>
 

    {% for new in category_list %}

        <div class="container">
            <a href="{% url 'home:detail' new.slug %}">
                <h4><b>{{ new.title }}</b></h4>
                <img src="{{ new.image.url }}" alt="" style="width: 700px; height: 500px;">
            </a>
            <b><p>Date: {{ new.created_at }} | Views: {{ new.views }}</p></b>
            <hr>
            <br>
            <br>
            
        </div>

    {% endfor %}

{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Contact Us
{% endblock title %}        

{% block menu %}
    <a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for category in kategoriyalar %}
        <a href="{% url 'home:category' category.slug %}" class="nav-item nav-link">{{ category.name }}</a>
    {% endfor %}

    <a href="{% url 'home:contact' %}" class="nav-item nav-link active">Contact Us</a>
{% endblock menu %}


{% block content %}
  

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                    <li class="breadcrumb-item active">Contact</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        

        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-4">
                        <div class="form">
                            <form method="POST">
                            {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" name="name" placeholder="Your Name" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" name="email" placeholder="Your Email/Phone" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="subject" placeholder="Subject" />
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" name="message" placeholder="Message"></textarea>
                                </div>
                                <div><button class="btn" type="submit">Send Message</button></div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3020.985767636229!2d-73.52689268518203!3d40.78432704112558!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c281127307115f%3A0x90d5abaf2f0279de!2sTerry%20Ln%2C%20Jericho%2C%20NY%2011753%2C%20USA!5e0!3m2!1sen!2sbd!4v1580837516748!5m2!1sen!2sbd" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="contact-info">
                            <h3>Get in Touch</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum quam ac mi viverra dictum. In efficitur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus.
                            </p>
                            <p><i class="fa fa-map-marker"></i>{{ about.locations }}</p>
                                <p><i class="fa fa-envelope"></i>{{ about.email }}</p>
                                <p><i class="fa fa-phone"></i>{{ about.phone }}</p>

                                <div class="social">
                                    <a href="{{ about.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a>
                                    <a href="{{ about.facebook }}" target="_blank"><i class="fab fa-facebook"></i></a>
                                    <a href="{{ about.linkedin }}" target="_blank"><i class="fab fa-linkedin"></i></a>
                                    <a href="{{ about.instagram }}" target="_blank"><i class="fab fa-instagram"></i></a>
                                    <a href="{{ about.youtube }}" target="_blank"><i class="fab fa-youtube"></i></a>
                                </div>
                                
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
        
    
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
delete page
{% endblock title %}

{% block menu %}
    <a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for category in kategoriyalar %}
        <a href="{% url 'home:category' category.id %}" class="nav-item nav-link">{{ category.name }}</a>
    {% endfor %}

    <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
{% endblock menu %}


{% block content %}

<h1><b>Delete News</b></h1>
<br>
<br>
<hr>
<br>
<br>

    <h1>Rostan ham bu xabarni o'chirishni xohlaysizmi?</h1>

    <div class="container">
        <h2><b>{{ news.title }}</b></h2>
        <img src="{{ news.image.url }}" alt="image" style="width: 800px; height: 500px;">
        <br>
        <br>
        {% if user.is_authenticated and user == news.author %}
            <a href="{% url 'home:delete-post' news.slug  %}" class="btn btn-info">O'chirish</a>
            <a href="{% url 'home:detail'  news.slug %}" class="btn btn-info">Orqaga</a>
        {% endif %}
    </div>
    <br>
    <br>
    <br>
    <hr>
    <br>
    <br>
    <br>

{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
detail page
{% endblock title %}

{% block menu %}
    <a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for category in kategoriyalar %}
        <a href="{% url 'home:category' category.slug %}" class="nav-item nav-link">{{ category.name }}</a>
    {% endfor %}

    <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
{% endblock menu %}


{% block content %}

<h1><b>Detail News</b></h1>
<br>
<br>
<hr>
<br>
<br>



    <div class="container">
        <h2><b>{{ news.title }}</b></h2>
        <img src="{{ news.image.url }}" alt="image" style="width: 800px; height: 500px;">
        {% if user.is_authenticated and user == news.author %}
            <a href="{% url 'home:delete' news.slug  %}" class="btn btn-info">O'chirish</a>
            <a href="{% url 'home:newupdate'  news.slug %}" class="btn btn-info">Yangilash</a>
        {% endif %}
        <br>    
        <br>

        <b><p>Date: {{ news.created_at }} | Views: {{ news.views }}</p></b>
        <br>
        <br>
        <br>

        <p>{{ news.body|safe }}</p>

    </div>
    <br>
    <br>
    <br>
    <hr>
    <br>
    <br>
    <br>



<div class="col-md-4">
    <div class="sidebar">
        <div class="sidebar-widget">
            <h2><i class="fas fa-align-justify"></i></h2>
            <div class="category">
                <ul class="fa-ul">
                </ul>
            </div>
        </div>

        <div class="sidebar-widget">
            <div class="tags">
            </div>
        </div>

    <div class="sidebar-widget">
        {% if ads_one %}
            {% for ads in ads_one %}
                <div class="image">
                    <a href="{{ ads.link }}"><img src="{{ ads.image.url }}" alt="Image"></a><br><br>
                </div>
            {% endfor %}
        {% endif %}
    </div>


    <div class="sidebar-widget">

        <div class="image">
            <div class="row">
                {% if ads_two %}
                    {% for ads in ads_two %}
                <div class="col-sm-6">
                    <a href="{{ ads.link }}"><img src="{{ ads.image.url }}" alt="Image"></a>
                </div>
                    {% endfor %}
                {% endif %}        
            </div>
        </div>
    </div>
        

    </div>
</div>
    
{% endblock content %}

templates/new_create.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
create news
{% endblock title %}

{% block content %}


<h2>Please Create Post</h2>

    <form method="post" class="container" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="container">
            {{ form.as_p }}
        </div>
        <input type="submit" name="submit" value="Create">
    </form>
    
<a href="{% url 'home:home' %}" class="btn btn-info">Back</a>


{% endblock content %}

templates/new_update.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
update news
{% endblock title %}

{% block content %}


<h2>Please Update Post</h2>

    <form method="post" class="container" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="container">
            {{ form.as_p }}
        </div>

        <input type="submit" name="submit" value="Update">
    </form>
    
<a href="{% url 'home:home' %}" class="btn btn-info">Back</a>


{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
search page
{% endblock title %}


{% block menu %}
    <a href="{% url 'home:home' %}" class="nav-item nav-link  ">Home</a>
    {% for category in kategoriyalar %}
        <a href="{% url 'home:category' category.slug %}" class="nav-item nav-link" >{{ category.name }}</a>
    {% endfor %}

    <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
{% endblock menu %}


{% block content %}

 <h1><b>Search results</b></h1>

{% for yangi in searchnews %}

    <div class="container">
        <a href="{% url 'home:detail' yangi.slug %}">
            <h3><b>{{ yangi.title }}</b></h3>
            <img src="{{ yangi.image.url }}" alt="image" style="width: 700px; height: 500px;">
        </a>
        <b><p>Date: {{ yangi.created_at }} | Views: {{ yangi.views }}</p></b>
        <hr>
        <br>
        <br>
    </div>

{% endfor %}

{% endblock content %}